services:
  web:    
    image: riviga77/eoi-fastapi-web
    container_name: web
    ports:
      - "5173:5173"
    depends_on:
      inventario:
        condition: service_started
      pedidos:
        condition: service_started                  
        
  inventario:    
    image: riviga77/eoi-fastapi-inventario
    container_name: inventario
    ports:
      - "8000:8000"    
    depends_on:
      apm-server:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  pedidos:
    image: riviga77/eoi-fastapi-pedidos
    container_name: pedidos
    ports:
      - "8001:8001"
    depends_on:
      apm-server:
        condition: service_started      
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  postgres:
    image: postgres:latest
    volumes:
      - ./data_postgres:/var/lib/postgresql/data/
    container_name: postgres    
    expose:
      - "5432:5432"  
    env_file:
      - .env       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:latest    
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data_mongo:/data/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 10
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./data_redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elastic    
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.8.0
    container_name: apm-server    
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
      - kibana shitless