services:
  inventario:
    build: inventario
    image: riviga77/eoi-fastapi-inventario
    container_name: inventario
    ports:
      - "8000:8000"
    volumes:
      - ./inventario:/code
    depends_on:
      apm-server:
        condition: service_started
      postgres_inv:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  pedidos:
    build: pedidos
    image: riviga77/eoi-fastapi-pedidos
    container_name: pedidos
    ports:
      - "8001:8001"
    volumes:
      - ./pedidos:/code
    depends_on:
      apm-server:
        condition: service_started      
      postgres_ped:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  postgres_inv:
    image: postgres:latest
    volumes:
      - ./data_postgres_inv:/var/lib/postgresql/data/
    container_name: postgres_inv    
    expose:
      - "5432:5432"  
    env_file:
      - .env       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 10

  postgres_ped:
    image: postgres:latest
    volumes:
      - ./data_postgres_ped:/var/lib/postgresql/data/
    container_name: postgres_ped    
    expose:
      - "5432:5432"  
    env_file:
      - .env       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 10
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./data_redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elastic    
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.8.0
    container_name: apm-server    
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
      - kibana 
